apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch-shared-replica"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse-server
  configuration:
    zookeeper:
      nodes:
        - host: zookeepers
    clusters:
      - name: "example"
        layout:
          shardsCount: 2
          replicasCount: 2
    settings:
      compression/case/method: zstd
    users:
      default/password: qwerty!234
      default/networks/ip:
        - "::"
        - "127.0.0.1"
        - "0.0.0.0/0"
      default/profile: default
      default/quota: default
  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
    podTemplates:
      - name: clickhouse-server
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.2.1-alpine
