apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "tabeldata"
spec:
  configuration:
    clusters:
      - name: "tabeldata"
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      compression/case/method: zstd
    users:
      default/password: qwerty!234
      default/networks/ip:
        - "::"
        - "127.0.0.1"
        - "0.0.0.0/0"
      default/profile: default
      default/quota: default
